server {
    listen 80 default_server;
    server_name localhost;

    root /var/www/tabletkovbot/public;
    index index.php;

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    location /webhook {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/tabletkovbot/public/index.php;
    }

    location ~ /\. {
        deny all;
    }
}
