server {
    listen 80 default_server;
    server_name localhost;  # укажите ваш реальный домен или IP

    root /var/www/tabletkovbot/src/Public;
    index webhook.php;

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    location /webhook {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/tabletkovbot/src/Public/webhook.php;
    }

    location ~ /\. {
        deny all;
    }
}
